import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TimelineProvider from "@/context/TimelineProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Keen Keeper",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <TimelineProvider>{children}</TimelineProvider>
      </body>
    </html>
  );
}
